### ISSUE TITLE
Missing mapping in block_id_to_item_id_map.json

### ISSUE THREAD

**Issue by smartcmd** [pmmp/bds-mod-mapping#6]
When I'm using this mapping, I noticed that there are some missing mappings.
Here are the missing mappings:

- **All** the hanging_sign (like `minecraft:bamboo_hanging_sign`)
- `minecraft:bamboo_door`
- `minecraft:cherry_door`

This looks like a BDS-related bug, because when I'm using my own data-dump tool, the same issue appeared.

Should we fix it through adding a special check like that?
https://github.com/AllayMC/DataExtractor/commit/2169f0ac56e41119c77e294fec867f2d9d786bcc

**Comment by dktapps** [comment]
block_id_to_item_id_map is intended for looking up item save IDs for blocks saved as blockstates in items. These items are not saved that way (they are just saved as regular items), so they aren't present in this file. Serialization for these blocks has to be implemented in a special manner.

Similar behaviour exists with other door blocks - they have invalid minecraft:item.door style IDs which are not intended to be used on disk.

**Comment by smartcmd** [comment]
OK, thanks
